# Generated by Django 6.0.4 on 2026-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='icu_beds_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_beds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
