# Generated by Django 6.0.4 on 2026-04-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='Chronic conditions (diabetes, hypertension, etc.)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Current medications being taken'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='family_medical_history',
            field=models.TextField(blank=True, help_text='Family history of diseases'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='notes_for_doctor',
            field=models.TextField(blank=True, help_text='Additional notes for doctors'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='number_of_children',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_communication',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default='email', help_text='Preferred method for appointment reminders', max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='secondary_emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former Smoker'), ('active', 'Active Smoker')], max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='surgical_history',
            field=models.TextField(blank=True, help_text='Previous surgeries and procedures'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Drug and food allergies'),
        ),
    ]
