# Generated by Django 6.0.4 on 2026-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_patient_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='alcohol_consumption',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='chronic_diseases',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='family_medical_history',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='last_checkup_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='notes_for_doctor',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='preferred_communication',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='secondary_emergency_contact',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='smoking_status',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='surgical_history',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='weight',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
    ]
